FROM node:20.11-alpine as build

WORKDIR /app
COPY . /app

ENV VITE_URL=https://service.peifang.app

RUN npm install
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/custom.conf
EXPOSE 80
CMD ["nginx","-g","daemon off;"]